userbuilding:
    pattern:  /userbuilding
    defaults: { _controller: FTRWebBundle:Userbuilding:index }
    
addData:
    pattern: /add/{id}
    defaults: { _controller: FTRWebBundle:Userbuilding:addData ,'id' :null }
    
saveData:
    pattern: /save/{id}
    defaults: { _controller: FTRWebBundle:Userbuilding:saveData ,'id' :null }
    
updateUserProfile:
    pattern: /check
    defaults: { _controller: FTRWebBundle:Userbuilding:updateUserProfile }
    
autoSaveForm:
    pattern: /autosave/{id}/{type}
    defaults: { _controller: FTRWebBundle:Userbuilding:autoSaveForm,'type' :null }

getDistrict:
    pattern: /getdistrict/{province}
    defaults: { _controller: FTRWebBundle:Userbuilding:getDistrict, 'province' :null }

listBuilding:
    pattern: /list_building
    defaults: { _controller: FTRWebBundle:Userbuilding:listApartment, 'province' :null }

getProvince:
    pattern: /getprovince/{province}
    defaults: { _controller: FTRWebBundle:Userbuilding:getProvinceData, 'province' :null }

setDeleteImage:
    pattern: /deleteimage
    defaults: { _controller: FTRWebBundle:Userbuilding:setDeleteImage }