userbuilding:
    pattern:  /listap
    defaults: { _controller: FTRWebBundle:Userbuilding:index }
    
addData:
    pattern: /add/{id}
    defaults: { _controller: FTRWebBundle:Userbuilding:addData ,'id' :null }
    
saveData:
    pattern: /save/{id}
    defaults: { _controller: FTRWebBundle:Userbuilding:saveData ,'id' :null }
    
updateUserProfile:
    pattern: /check
    defaults: { _controller: FTRWebBundle:Userbuilding:updateUserProfile }
    
choosePicture:
    pattern: /choosepic/{id}
    defaults: { _controller: FTRWebBundle:Userbuilding:chooseFile }
    
uploadPicture:
    pattern: /choosepic
    defaults: { _controller: FTRWebBundle:Userbuilding:uploadFile }