userbuilding:
    pattern:  /userbuilding
    defaults: { _controller: FTRWebBundle:Userbuilding:index }
    
addData:
    pattern: /add/{id}
    defaults: { _controller: FTRWebBundle:Userbuilding:addData ,'id' :null }

addNewBuildData:
    pattern: /addbuilding
    defaults: { _controller: FTRWebBundle:Userbuilding:addNewData }
    
saveData:
    pattern: /save/{id}
    defaults: { _controller: FTRWebBundle:Userbuilding:saveData ,'id' :null }
    
updateUserProfile:
    pattern: /check
    defaults: { _controller: FTRWebBundle:Userbuilding:updateUserProfile }
    
autoSaveForm:
    pattern: /autosave/{id}/{type}
    defaults: { _controller: FTRWebBundle:Userbuilding:autoSaveForm,'type' :null,'id' :null }

getDistrict:
    pattern: /getdistrict/{province}
    defaults: { _controller: FTRWebBundle:Userbuilding:getDistrict, 'province' :null }

listBuilding:
    pattern: /list_building
    defaults: { _controller: FTRWebBundle:Userbuilding:listApartment, 'province' :null }

getProvince:
    pattern: /getprovince/{province}
    defaults: { _controller: FTRWebBundle:Userbuilding:getProvinceData, 'province' :null }

setDeleteImage:
    pattern: /deleteimage
    defaults: { _controller: FTRWebBundle:Userbuilding:setDeleteImage }

changePassUser:
    pattern: /changepassword
    defaults: { _controller: FTRWebBundle:Userbuilding:changePassUserProfile }

deleteData:
    pattern: /deletebuild
    defaults: { _controller: FTRWebBundle:Userbuilding:deleteBuilding }

listApartment:
    pattern: /listapartment
    defaults: { _controller: FTRWebBundle:Userbuilding:listApartment }

addNew:
    pattern: /addnew
    defaults: { _controller: FTRWebBundle:Userbuilding:addNew }

saveAddNew:
    pattern: /saveaddnew
    defaults: { _controller: FTRWebBundle:Userbuilding:postAddNew }

addNewRoom:
    pattern: /addnewroom/{id}
    defaults: { _controller: FTRWebBundle:Userbuilding:addNewRoom }

addNewGallery:
    pattern: /addnewgaller/{id}
    defaults: { _controller: FTRWebBundle:Userbuilding:addNewGallery }

addNewOther:
    pattern: /addnewother/{id}
    defaults: { _controller: FTRWebBundle:Userbuilding:addNewOther }
    
