<?php

namespace FTR\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Site_detailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Site_detailRepository extends EntityRepository
{
}