FTRAdminBundle:
    resource: "@FTRAdminBundle/Resources/config/routing.yml"
    prefix:   /

FTRWebBundle:
    resource: "@FTRWebBundle/Resources/config/routing.yml"
    prefix:   /

FTRWebBundle_UserBuilding:
    resource: "@FTRWebBundle/Resources/config/routing/userbuilding.yml"
    prefix:   /publish

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
