<?php

namespace FTR\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Ads_ControlRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Ads_ControlRepository extends EntityRepository
{
}