<?php

namespace FTR\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Banner_countRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Banner_countRepository extends EntityRepository
{
}