<?php

namespace FTR\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * facilitylistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FacilitylistRepository extends EntityRepository
{
    /*
    * Get data Facilitylist
    */
    public function getData($limit, $offset, $textSearch, &$count, $orderBy){
        $sql = "
            SELECT
              f
            FROM FTRWebBundle:Facilitylist f
            WHERE f.deleted = 0
        ";
        if (!empty($textSearch) && $textSearch != ''){
            $sql = "
                $sql
                AND f.id LIKE '%$textSearch%'
                OR f.facility_name LIKE '%$textSearch%'
                OR f.facility_type LIKE '%$textSearch%'
                OR f.display LIKE '%$textSearch%'
            ";

            //นับจำนวนใหม่
            $count = count($this -> getEntityManager() -> createQuery($sql)-> getResult());
        }
        $sql = "
                $sql
                ORDER BY f.$orderBy
            ";
        return $this -> getEntityManager() -> createQuery($sql) -> setFirstResult($offset) -> setMaxResults($limit) -> getResult();

    }
}