<?php

namespace FTR\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Ftr_logdetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Ftr_logdetailRepository extends EntityRepository
{
}