<?php

namespace FTR\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MenusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenusRepository extends EntityRepository
{
}