<?php

namespace FTR\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Pay_typeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Pay_typeRepository extends EntityRepository
{
    /*
     * Get data pay_type
     */
    public function getDataPayType($limit, $offset, $textSearch, &$count, $orderBy){
        $sql = "
            SELECT
              p
            FROM FTRWebBundle:Pay_type p
            WHERE p.deleted = 0
        ";
        if (!empty($textSearch) && $textSearch != ''){
            $sql = "
                $sql
                AND p.id LIKE '%$textSearch%'
                OR p.typename LIKE '%$textSearch%'
            ";

            //นับจำนวนใหม่
            $count = count($this -> getEntityManager() -> createQuery($sql)-> getResult());
        }
        $sql = "
                $sql
                ORDER BY p.$orderBy
            ";
        return $this -> getEntityManager() -> createQuery($sql) -> setFirstResult($offset) -> setMaxResults($limit) -> getResult();

    }
}