<?php

namespace FTR\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\QueryException;
/**
 * ZoneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ZoneRepository extends EntityRepository
{
    /*
     * Get data zone
     */
    public function getDataZone($limit, $offset){
        $sql = "
            SELECT
              z
            FROM FTRWebBundle:Zone z
        ";
        return $this -> getEntityManager() -> createQuery($sql) -> setFirstResult($offset) -> setMaxResults($limit) -> getResult();

    }

}