ads_control:
    pattern:  /
    defaults: { _controller: "FTRAdminBundle:Ads_Control:index" }

ads_control_show:
    pattern:  /show
    defaults: { _controller: "FTRAdminBundle:Ads_Control:show" }

ads_control_new:
    pattern:  /new
    defaults: { _controller: "FTRAdminBundle:Ads_Control:new" }

ads_control_create:
    pattern:  /create
    defaults: { _controller: "FTRAdminBundle:Ads_Control:create" }
    requirements: { _method: post }

ads_control_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "FTRAdminBundle:Ads_Control:edit" }

ads_control_update:
    pattern:  /{id}/update
    defaults: { _controller: "FTRAdminBundle:Ads_Control:update" }
    requirements: { _method: post }
