building_site:
    pattern:  /
    defaults: { _controller: FTRAdminBundle:Building_site:index }
    
building_site_show:
    pattern:  /show
    defaults: { _controller: FTRAdminBundle:Building_site:show }
    
building_site_new:
    pattern:  /new
    defaults: { _controller: FTRAdminBundle:Building_site:new }
    
building_site_create:
    pattern:  /create
    defaults: { _controller: FTRAdminBundle:Building_site:create }
    
building_site_edit:
    pattern:  /{id}/edit
    defaults: { _controller: FTRAdminBundle:Building_site:edit }
    
building_site_update:
    pattern:  /{id}/update
    defaults: { _controller: FTRAdminBundle:Building_site:update }
    
building_site_delete:
    pattern:  /{id}/delete
    defaults: { _controller: FTRAdminBundle:Building_site:delete }