facilitylist:
    pattern:  /
    defaults: { _controller: "FTRAdminBundle:Facilitylist:index" }

facilitylist_show:
    pattern:  /show
    defaults: { _controller: "FTRAdminBundle:Facilitylist:show" }

facilitylist_new:
    pattern:  /new
    defaults: { _controller: "FTRAdminBundle:Facilitylist:new" }

facilitylist_create:
    pattern:  /create
    defaults: { _controller: "FTRAdminBundle:Facilitylist:create" }
    requirements: { _method: post }

facilitylist_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "FTRAdminBundle:Facilitylist:edit" }

facilitylist_update:
    pattern:  /{id}/update
    defaults: { _controller: "FTRAdminBundle:Facilitylist:update" }
    requirements: { _method: post }
