facility2site:
    pattern:  /
    defaults: { _controller: "FTRAdminBundle:Facility2site:index" }

facility2site_show:
    pattern:  /{id}/show
    defaults: { _controller: "FTRAdminBundle:Facility2site:show" }

facility2site_new:
    pattern:  /new
    defaults: { _controller: "FTRAdminBundle:Facility2site:new" }

facility2site_create:
    pattern:  /create
    defaults: { _controller: "FTRAdminBundle:Facility2site:create" }
    requirements: { _method: post }

facility2site_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "FTRAdminBundle:Facility2site:edit" }

facility2site_update:
    pattern:  /{id}/update
    defaults: { _controller: "FTRAdminBundle:Facility2site:update" }
    requirements: { _method: post }

facility2site_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "FTRAdminBundle:Facility2site:delete" }
    requirements: { _method: post }
