facility2site_show:
    pattern:  /{id}/show
    defaults: { _controller: "FTRAdminBundle:Facility2site:show" }

facility2site_create:
    pattern:  /create
    defaults: { _controller: "FTRAdminBundle:Facility2site:create" }
    requirements: { _method: post }
