image_show:
    pattern:  /{id}/show
    defaults: { _controller: "FTRAdminBundle:Image:show" }

image_create:
    pattern:  /create
    defaults: { _controller: "FTRAdminBundle:Image:create" }
    requirements: { _method: post }