user_admin:
    pattern:  /
    defaults: { _controller: FTRAdminBundle:User_admin:index }
    
admin_create:
    pattern:  /create
    defaults: { _controller: FTRAdminBundle:User_admin:create }
    
admin_show:
    pattern:  /show
    defaults: { _controller: FTRAdminBundle:User_admin:show }

admin_edit:
    pattern:  /{id}/edit
    defaults: { _controller: FTRAdminBundle:User_admin:edit }

admin_update:
    pattern:  /update/{id}
    defaults: { _controller: FTRAdminBundle:User_admin:update }
    
admin_delete:
    pattern:  /{id}/delete
    defaults: { _controller: FTRAdminBundle:User_admin:delete }