pay_type:
    pattern:  /
    defaults: { _controller: "FTRAdminBundle:Pay_type:index" }

pay_type_new:
    pattern:  /new
    defaults: { _controller: "FTRAdminBundle:Pay_type:new" }

pay_type_create:
    pattern:  /create
    defaults: { _controller: "FTRAdminBundle:Pay_type:create" }
    requirements: { _method: post }

pay_type_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "FTRAdminBundle:Pay_type:edit" }

pay_type_update:
    pattern:  /{id}/update
    defaults: { _controller: "FTRAdminBundle:Pay_type:update" }
    requirements: { _method: post }
