
roomtype2site_show:
    pattern:  /{id}/show
    defaults: { _controller: "FTRAdminBundle:Roomtype2site:show" }

roomtype2site_create:
    pattern:  /create
    defaults: { _controller: "FTRAdminBundle:Roomtype2site:create" }
    requirements: { _method: post }

roomtype2site_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "FTRAdminBundle:Roomtype2site:edit" }