user_owner:
    pattern:  /
    defaults: { _controller: "FTRAdminBundle:User_owner:index" }

user_owner_show:
    pattern:  /show
    defaults: { _controller: "FTRAdminBundle:User_owner:show" }

user_owner_new:
    pattern:  /new
    defaults: { _controller: "FTRAdminBundle:User_owner:new" }

user_owner_create:
    pattern:  /create
    defaults: { _controller: "FTRAdminBundle:User_owner:create" }
    requirements: { _method: post }

user_owner_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "FTRAdminBundle:User_owner:edit" }

user_owner_update:
    pattern:  /{id}/update
    defaults: { _controller: "FTRAdminBundle:User_owner:update" }
    requirements: { _method: post }

user_owner_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "FTRAdminBundle:User_owner:delete" }
    requirements: { _method: post }
