FTRAdminBundle_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: FTRAdminBundle:Default:index }
    
FTRAdminBundle_Building_site:
    resource: "@FTRAdminBundle/Resources/config/routing/building_site.yml"
    prefix:   /building_site

FTRWebBundle_building_type:
    resource: "@FTRAdminBundle/Resources/config/routing/building_type.yml"
    prefix:   /building_type

FTRAdminBundle_facility2site:
    resource: "@FTRAdminBundle/Resources/config/routing/facility2site.yml"
    prefix:   /facility2site

FTRAdminBundle_facilitylist:
    resource: "@FTRAdminBundle/Resources/config/routing/facilitylist.yml"
    prefix:   /facilitylist
    
FTRAdminBundle_image:
    resource: "@FTRAdminBundle/Resources/config/routing/image.yml"
    prefix:   /image

FTRAdminBundle_nearly_location:
    resource: "@FTRAdminBundle/Resources/config/routing/nearly_location.yml"
    prefix:   /nearly_location

FTRAdminBundle_nearly_type:
    resource: "@FTRAdminBundle/Resources/config/routing/nearly_type.yml"
    prefix:   /nearly_type

FTRAdminBundle_nearly2site:
    resource: "@FTRAdminBundle/Resources/config/routing/nearly2site.yml"
    prefix:   /nearly2site
    
FTRAdminBundle_pay_type:
    resource: "@FTRAdminBundle/Resources/config/routing/pay_type.yml"
    prefix:   /pay_type
    
FTRAdminBundle_roomtype2site:
    resource: "@FTRAdminBundle/Resources/config/routing/roomtype2site.yml"
    prefix:   /roomtype2site
    
FTRAdminBundle_roomtype:
    resource: "@FTRAdminBundle/Resources/config/routing/roomtype.yml"
    prefix:   /roomtype
        
FTRAdminBundle_zone:
    resource: "@FTRAdminBundle/Resources/config/routing/zone.yml"
    prefix:   /zone

FTRAdminBundle_user_admin:
    resource: "@FTRAdminBundle/Resources/config/routing/user_admin.yml"
    prefix:   /user_admin
    
FTRAdminBundle_user_owner:
    resource: "@FTRAdminBundle/Resources/config/routing/user_owner.yml"
    prefix:   /user_owner

FTRAdminBundle_user_level:
    resource: "@FTRAdminBundle/Resources/config/routing/user_level.yml"
    prefix:   /user_level
    
# Routing of Backend Panel
# Creator : MICK
# Createtime : 2012-08-28
#

FTRAdminBundle_signin:
    pattern:  /signin
    defaults: { _controller: FTRAdminBundle:Panel:signin } 

FTRAdminBundle_logout:
    pattern:  /logout
    defaults: { _controller: FTRAdminBundle:Panel:logout }