FTRAdminBundle_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: FTRAdminBundle:Default:index }
    
FTRAdminBundle_Building_site:
    resource: "@FTRAdminBundle/Resources/config/routing/building_site.yml"
    prefix:   /building_site
    
FTRWebBundle_building_type:
    resource: "@FTRAdminBundle/Resources/config/routing/building_type.yml"
    prefix:   /building_type

FTRAdminBundle_facility2site:
    resource: "@FTRAdminBundle/Resources/config/routing/facility2site.yml"
    prefix:   /facility2site

FTRAdminBundle_facilitylist:
    resource: "@FTRAdminBundle/Resources/config/routing/facilitylist.yml"
    prefix:   /facilitylist
    
FTRAdminBundle_image:
    resource: "@FTRAdminBundle/Resources/config/routing/image.yml"
    prefix:   /image

FTRAdminBundle_nearly_location:
    resource: "@FTRAdminBundle/Resources/config/routing/nearly_location.yml"
    prefix:   /nearly_location

FTRAdminBundle_nearly_type:
    resource: "@FTRAdminBundle/Resources/config/routing/nearly_type.yml"
    prefix:   /nearly_type

FTRAdminBundle_nearly2site:
    resource: "@FTRAdminBundle/Resources/config/routing/nearly2site.yml"
    prefix:   /nearly2site
    
FTRAdminBundle_pay_type:
    resource: "@FTRAdminBundle/Resources/config/routing/pay_type.yml"
    prefix:   /pay_type
    
FTRAdminBundle_roomtype2site:
    resource: "@FTRAdminBundle/Resources/config/routing/roomtype2site.yml"
    prefix:   /roomtype2site
    
FTRAdminBundle_roomtype:
    resource: "@FTRAdminBundle/Resources/config/routing/roomtype.yml"
    prefix:   /roomtype
        
FTRAdminBundle_zone:
    resource: "@FTRAdminBundle/Resources/config/routing/zone.yml"
    prefix:   /zone

    
# Routing of Backend Panel
# Creator : MICK
# Createtime : 2012-08-28
# 
FTRAdminBundle_panel:
    pattern:  /ftr_panel/
    defaults: { _controller: FTRAdminBundle:Panel:index } 

FTRAdminBundle_signin:
    pattern:  /ftr_panel/signin
    defaults: { _controller: FTRAdminBundle:Panel:signin } 

FTRAdminBundle_logout:
    pattern:  /ftr_panel/logout
    defaults: { _controller: FTRAdminBundle:Panel:logout } 

FTRAdminBundle_Dashboard:
    pattern:  /ftr_panel/dashboard
    defaults: { _controller: FTRAdminBundle:Dashboard:index } 
    
FTRAdminBundle_Zonelists:
    pattern:  /ftr_panel/zonelists
    defaults: { _controller: FTRAdminBundle:zonelists:index } 
    
FTRAdminBundle_Buildingtypelists:
    pattern:  /ftr_panel/buildingtypelists
    defaults: { _controller: FTRAdminBundle:buildingtypelists:index } 
    
FTRAdminBundle_Buildingsitelists:
    pattern:  /ftr_panel/buildingsitelists
    defaults: { _controller: FTRAdminBundle:buildingsitelists:index }
    
FTRAdminBundle_Facilitylists:
    pattern:  /ftr_panel/facilitylists
    defaults: { _controller: FTRAdminBundle:facilitylists:index } 
    
FTRAdminBundle_Roomtypelists:
    pattern:  /ftr_panel/roomtypelists
    defaults: { _controller: FTRAdminBundle:roomtypelists:index } 
    
FTRAdminBundle_Nearlytypelists:
    pattern:  /ftr_panel/nearlytypelists
    defaults: { _controller: FTRAdminBundle:nearlytypelists:index } 
    
FTRAdminBundle_Nearlylocationlists:
    pattern:  /ftr_panel/nearlylocationlists
    defaults: { _controller: FTRAdminBundle:nearlylocationlists:index } 
    
FTRAdminBundle_Paytypelists:
    pattern:  /ftr_panel/paytypelists
    defaults: { _controller: FTRAdminBundle:paytypelists:index } 
    
FTRAdminBundle_Useradminlists:
    pattern:  /ftr_panel/useradminlists
    defaults: { _controller: FTRAdminBundle:useradminlists:index } 

FTRAdminBundle_Createadminlists:
    pattern:  /ftr_panel/createadminlists
    defaults: { _controller: FTRAdminBundle:useradminlists:create } 

FTRAdminBundle_Showadminlists:
    pattern:  /ftr_panel/{id}/showdata
    defaults: { _controller: FTRAdminBundle:useradminlists:showdata }
  
FTRAdminBundle_Userownerlists:
    pattern:  /ftr_panel/userownerlists
    defaults: { _controller: FTRAdminBundle:userownerlists:index } 
    
FTRAdminBundle_Createownerlists:
    pattern:  /ftr_panel/createownerlists
    defaults: { _controller: FTRAdminBundle:userownerlists:create } 
    
FTRAdminBundle_Sitedetail:
    pattern:  /ftr_panel/sitedetail
    defaults: { _controller: FTRAdminBundle:sitedetail:index } 
    
FTRAdminBundle_Advertisingdetail:
    pattern:  /ftr_panel/advertisingdetail
    defaults: { _controller: FTRAdminBundle:advertisingdetail:index } 