FTRAdminBundle_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: FTRAdminBundle:Default:index }
    
FTRAdminBundle_Building_site:
    resource: "@FTRAdminBundle/Resources/config/routing/building_site.yml"
    prefix:   /building_site

FTRAdminBundle_building_type:
    resource: "@FTRAdminBundle/Resources/config/routing/building_type.yml"
    prefix:   /building_type

FTRAdminBundle_facility2site:
    resource: "@FTRAdminBundle/Resources/config/routing/facility2site.yml"
    prefix:   /facility2site

FTRAdminBundle_facilitylist:
    resource: "@FTRAdminBundle/Resources/config/routing/facilitylist.yml"
    prefix:   /facilitylist
    
FTRAdminBundle_image:
    resource: "@FTRAdminBundle/Resources/config/routing/image.yml"
    prefix:   /image

FTRAdminBundle_nearly_location:
    resource: "@FTRAdminBundle/Resources/config/routing/nearly_location.yml"
    prefix:   /nearly_location

FTRAdminBundle_nearly_type:
    resource: "@FTRAdminBundle/Resources/config/routing/nearly_type.yml"
    prefix:   /nearly_type

FTRAdminBundle_nearly2site:
    resource: "@FTRAdminBundle/Resources/config/routing/nearly2site.yml"
    prefix:   /nearly2site
    
FTRAdminBundle_pay_type:
    resource: "@FTRAdminBundle/Resources/config/routing/pay_type.yml"
    prefix:   /pay_type
    
FTRAdminBundle_roomtype2site:
    resource: "@FTRAdminBundle/Resources/config/routing/roomtype2site.yml"
    prefix:   /roomtype2site
    
FTRAdminBundle_roomtype:
    resource: "@FTRAdminBundle/Resources/config/routing/roomtype.yml"
    prefix:   /roomtype
        
FTRAdminBundle_zone:
    resource: "@FTRAdminBundle/Resources/config/routing/zone.yml"
    prefix:   /zone

FTRAdminBundle_user_admin:
    resource: "@FTRAdminBundle/Resources/config/routing/user_admin.yml"
    prefix:   /user_admin
    
FTRAdminBundle_user_owner:
    resource: "@FTRAdminBundle/Resources/config/routing/user_owner.yml"
    prefix:   /user_owner

FTRAdminBundle_user_level:
    resource: "@FTRAdminBundle/Resources/config/routing/user_level.yml"
    prefix:   /user_level

FTRAdminBundle_manage_resource:
    resource: "@FTRAdminBundle/Resources/config/routing/manage_resource.yml"
    prefix:   /manage_resource

# Routing of Backend Panel
# Creator : MICK
# Createtime : 2012-08-28
#
FTRAdminBundle_panel:
    pattern: /
    defaults: { _controller: FTRAdminBundle:Panel:index }

FTRAdminBundle_signin:
    pattern:  /signin
    defaults: { _controller: FTRAdminBundle:Panel:signin }

FTRAdminBundle_logout:
    pattern:  /logout
    defaults: { _controller: FTRAdminBundle:Panel:logout }

FTRAdminBundle_Dashboard:
    pattern:  /dashboard
    defaults: { _controller: FTRAdminBundle:Dashboard:index }

FTRAdminBundle_Zonelists:
    pattern:  /zonelists
    defaults: { _controller: FTRAdminBundle:zonelists:index }

FTRAdminBundle_Buildingtypelists:
    pattern:  /buildingtypelists
    defaults: { _controller: FTRAdminBundle:buildingtypelists:index }

FTRAdminBundle_Buildingsitelists:
    pattern:  /buildingsitelists
    defaults: { _controller: FTRAdminBundle:buildingsitelists:index }

FTRAdminBundle_Facilitylists:
    pattern:  /facilitylists
    defaults: { _controller: FTRAdminBundle:facilitylists:index }

FTRAdminBundle_Roomtypelists:
    pattern:  /roomtypelists
    defaults: { _controller: FTRAdminBundle:roomtypelists:index }

FTRAdminBundle_Nearlytypelists:
    pattern:  /nearlytypelists
    defaults: { _controller: FTRAdminBundle:nearlytypelists:index }

FTRAdminBundle_Nearlylocationlists:
    pattern:  /nearlylocationlists
    defaults: { _controller: FTRAdminBundle:nearlylocationlists:index }

FTRAdminBundle_Paytypelists:
    pattern:  /paytypelists
    defaults: { _controller: FTRAdminBundle:paytypelists:index }

FTRAdminBundle_Useradminlists:
    pattern:  /useradminlists
    defaults: { _controller: FTRAdminBundle:useradminlists:index }

FTRAdminBundle_Createadminlists:
    pattern:  /createadminlists
    defaults: { _controller: FTRAdminBundle:useradminlists:create }

FTRAdminBundle_Showadminlists:
    pattern:  /ftr_panel/{id}/showdata
    defaults: { _controller: FTRAdminBundle:useradminlists:showdata }

FTRAdminBundle_Userownerlists:
    pattern:  /userownerlists
    defaults: { _controller: FTRAdminBundle:userownerlists:index }

FTRAdminBundle_Createownerlists:
    pattern:  /createownerlists
    defaults: { _controller: FTRAdminBundle:userownerlists:create }

FTRAdminBundle_Sitedetail:
    pattern:  /sitedetail
    defaults: { _controller: FTRAdminBundle:sitedetail:index }

FTRAdminBundle_Advertisingdetail:
    pattern:  /advertisingdetail
    defaults: { _controller: FTRAdminBundle:advertisingdetail:index }

FTRAdminBundle_EditProfile:
    pattern:  /edit
    defaults: { _controller: FTRAdminBundle:Adminprofile:edit }

FTRAdminBundle_UpdateProfile:
    pattern:  /update/{id}
    defaults: { _controller: FTRAdminBundle:Adminprofile:update }