<?php

namespace FTR\WebBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Nearly2siteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Nearly2siteRepository extends EntityRepository
{
}