<?php

namespace FTR\WebBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Pay_typeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Pay_typeRepository extends EntityRepository
{
}