<?php

namespace FTR\WebBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * User_ownerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class User_ownerRepository extends EntityRepository
{
}