FTRWebBundle_homepage:
    pattern:  /
    defaults: { _controller: FTRWebBundle:Main:index }

FTRWebBundle_recom:
    pattern:  /slide
    defaults: { _controller: FTRWebBundle:Main:recom }
    
FTRWebBundle_search:
    pattern:  /search
    defaults: { _controller: FTRWebBundle:Search:search }
    
FTRWebBundle_detail:
    pattern:  /detail
    defaults: { _controller: FTRWebBundle:Detail:detail }
    
FTRWebBundle_publish:
    pattern:  /publish
    defaults: { _controller: FTRWebBundle:Publish:publish }
    
FTRWebBundle_contact:
    pattern:  /contact
    defaults: { _controller: FTRWebBundle:Contact:contact }

FTRWebBundle_newimg:
    pattern:  /contact/newimg
    defaults: { _controller: FTRWebBundle:Contact:newimg }

FTRWebBundle_sendcontact:
    pattern:  /contact/send
    defaults: { _controller: FTRWebBundle:Contact:sendContact }

FTRWebBundle_regis:
    pattern:  /regis
    defaults: { _controller: FTRWebBundle:Register:register }
    
FTRWebBundle_confirm:
    pattern:  /regis/confirm
    defaults: { _controller: FTRWebBundle:Register:RegisConfirm}
    
FTRWebBundle_regis_success:
    pattern:  /regis/success
    defaults: { _controller: FTRWebBundle:Register:regsuccess }
       
FTRWebBundle_login:
    pattern:  /login
    defaults: { _controller: FTRWebBundle:Security:login}
    
FTRWebBundle_loginpublish:
    pattern:  /loginpub
    defaults: { _controller: FTRWebBundle:Security:logPublish}

FTRWebBundle_logout:
    pattern:  /logout
    defaults: { _controller: FTRWebBundle:Security:logout}

TRWebBundle_reset:
    pattern:  /reset
    defaults: { _controller: FTRWebBundle:Reset:reset}
    
TRWebBundle_change:
    pattern:  /reset/change
    defaults: { _controller: FTRWebBundle:Reset:change}

TRWebBundle_chgconfirm:
    pattern:  /reset/change/confirm
    defaults: { _controller: FTRWebBundle:Reset:passchg}

FTRWebBundle_forget:
    pattern:  /forget
    defaults: { _controller: FTRWebBundle:Forget:forget}

FTRWebBundle_sendemail:
    pattern:  /sendemail
    defaults: { _controller: FTRWebBundle:Forget:sendEmail}

FTRWebBundle_forget_confirm:
    pattern:  /confirm
    defaults: { _controller: FTRWebBundle:Forget:confirm}

FTRWebBundle_list:
    pattern:  /list
    defaults: { _controller: FTRWebBundle:List:index}

FTRWebBundle_search_ampher:
    pattern:  /search/ampher
    defaults: { _controller: FTRWebBundle:Search:ampher}

#FTRWebBundle_sendmail_extest:
#    pattern:  /sendemail
#    defaults: { _controller: FTRWebBundle:Userbuilding:sendemail}