FTRWebBundle_homepage:
    pattern:  /
    defaults: { _controller: FTRWebBundle:Main:index }
    
FTRWebBundle_search:
    pattern:  /search
    defaults: { _controller: FTRWebBundle:Search:search }
    
FTRWebBundle_publish:
    pattern:  /publish
    defaults: { _controller: FTRWebBundle:Publish:publish }
    
FTRWebBundle_contact:
    pattern:  /contact
    defaults: { _controller: FTRWebBundle:Contact:contact }

FTRWebBundle_layout:
    pattern:  /layout
    defaults: { _controller: FTRWebBundle:Layout:layout }

FTRWebBundle_regis:
    pattern:  /regis
    defaults: { _controller: FTRWebBundle:Register:register }
    
FTRWebBundle_confirm:
    pattern:  /regis/confirm
    defaults: { _controller: FTRWebBundle:Register:RegisConfirm}
    
FTRWebBundle_login:
    pattern:  /login
    defaults: { _controller: FTRWebBundle:Security:login}

FTRWebBundle_logout:
    pattern:  /logout
    defaults: { _controller: FTRWebBundle:Security:logout}

TRWebBundle_reset:
    pattern:  /reset
    defaults: { _controller: FTRWebBundle:Reset:reset}

FTRWebBundle_forget:
    pattern:  /forget
    defaults: { _controller: FTRWebBundle:Forget:forget}

FTRWebBundle_sendemail:
    pattern:  /sendemail
    defaults: { _controller: FTRWebBundle:Forget:sendEmail}

FTRWebBundle_sendmail_extest:
    pattern:  /sendemail
    defaults: { _controller: FTRWebBundle:Userbuilding:sendemail}
