FTRWebBundle_homepage:
    pattern:  /
    defaults: { _controller: FTRWebBundle:Main:index }

FTRWebBundle_recom:
    pattern:  /slide
    defaults: { _controller: FTRWebBundle:Main:recom }
    
FTRWebBundle_search:
    pattern:  /search
#    pattern:  /ค้นหาหอพัก
    defaults: { _controller: FTRWebBundle:Search:search }

FTRWebBundle_detail:
    pattern:  /detail/{buildId}/{province}/{prefecture}/{slug}
    defaults: { _controller: FTRWebBundle:Detail:detail}
    
FTRWebBundle_publish:
    pattern:  /publish
#    pattern:  /ลงประกาศห้องพักฟรี
    defaults: { _controller: FTRWebBundle:Publish:publish }

FTRWebBundle_contact:
    pattern:  /contact
#    pattern:  /ติดต่อfindtheroom
    defaults: { _controller: FTRWebBundle:Contact:contact }

FTRWebBundle_newimg:
    pattern:  /contact/newimg
    defaults: { _controller: FTRWebBundle:Contact:newimg }

FTRWebBundle_sendcontact:
    pattern:  /contact/send
    defaults: { _controller: FTRWebBundle:Contact:sendContact }

FTRWebBundle_regis:
    pattern:  /regis
    defaults: { _controller: FTRWebBundle:Register:register }

FTRWebBundle_regisSendEmail:
    pattern:  /regisSendEmail
    defaults: { _controller: FTRWebBundle:Register:sendemail }

FTRWebBundle_confirm:
    pattern:  /regis/confirm
    defaults: { _controller: FTRWebBundle:Register:RegisConfirm}

FTRWebBundle_terms:
    pattern:  /term
    defaults: { _controller: FTRWebBundle:Register:terms}

FTRWebBundle_regis_success:
    pattern:  /regis/success
    defaults: { _controller: FTRWebBundle:Register:regsuccess }

FTRWebBundle_regis_alertemail:
    pattern:  /regis/alertemail
    defaults: { _controller: FTRWebBundle:Register:alertEmail }

FTRWebBundle_login:
    pattern:  /login
    defaults: { _controller: FTRWebBundle:Security:login}
    
FTRWebBundle_loginpublish:
    pattern:  /loginpub/{message}
    defaults: { _controller: FTRWebBundle:Security:logPublish}

FTRWebBundle_logout:
    pattern:  /logout
    defaults: { _controller: FTRWebBundle:Security:logout}

TRWebBundle_reset:
    pattern:  /reset/{userId}
    defaults: { _controller: FTRWebBundle:Reset:reset}

TRWebBundle_chgconfirm:
    pattern:  /reset/change/{userId}
    defaults: { _controller: FTRWebBundle:Reset:passchg}

FTRWebBundle_forget:
    pattern:  /forget
    defaults: { _controller: FTRWebBundle:Forget:forget}

FTRWebBundle_sendemail:
    pattern:  /sendemail
    defaults: { _controller: FTRWebBundle:Forget:sendEmail}

FTRWebBundle_forget_confirm:
    pattern:  /confirm
    defaults: { _controller: FTRWebBundle:Forget:confirm}

FTRWebBundle_list:
    pattern:  /list
    defaults: { _controller: FTRWebBundle:List:index}

FTRWebBundle_search_ampher:
    pattern:  /search/ampher
    defaults: { _controller: FTRWebBundle:Search:ampher}

FTRWebBundle_banner:
    pattern:  /ads
#    pattern:  /ลงโฆษณาหอพัก
    defaults: { _controller: FTRWebBundle:Banner:banner}

FTRWebBundle_loginFacebook:
    pattern:  /loginfacebook
    defaults: { _controller: FTRWebBundle:Security:loginFacebook}

#FTRWebBundle_sendmail_extest:
#    pattern:  /sendemail
#    defaults: { _controller: FTRWebBundle:Userbuilding:sendemail}

#peung
FTRWebBundle_defalut_countclick:
    pattern:  /countclick
    defaults: { _controller: FTRWebBundle:Default:countClick}

# DEV : MICK
# Date : 07/03/2013
# ใช้ตรวจสอบค่า Token จาก Email ในการ Confirm การสร้างห้องพักใหม่
FTRWebBundle_confirm_building:
    pattern:  /confirm_token/{id}/{token}
    defaults: { _controller: FTRWebBundle:ConfirmBuilding:validateConfirmBuildingToken}

# DEV : MICK
# Date : 07/03/2013
# แสดงผลการ validate confirm token จาก email
FTRWebBundle_confirm_result:
    pattern:  /confirm_result/{id}/{token}/{result}
    defaults: { _controller: FTRWebBundle:ConfirmBuilding:showResultValidate}

# DEV : MICK
# Date : 07/03/2013
# generate confirm token และ password update
FTRWebBundle_gen_confirm_code:
    pattern:  /gen_confirm_code/{id}
    defaults: { _controller: FTRWebBundle:ConfirmBuilding:genConfirmBuildingCode}

# DEV : MICK
# Date : 08/03/2013
# แสดง googlemap ขนาด 800x600 โดยส่งรายละเอียดดังนี้
# id, building name, building type, start price, end price, google lat, google long
FTRWebBundle_googlemap_view:
    pattern:  /googlemap_view/{id}
    defaults: { _controller: FTRWebBundle:Googlemap:sendToGooglemapView}
